packages:
  - 'packages/*'
  - 'examples/*'

blockExoticSubdeps: true

allowBuilds:
  better-sqlite3: true
  cbor-extract: false
  esbuild: true
  keccak: false
  msw: true
  sharp: true
  simple-git-hooks: true
  workerd: true

catalog:
  typescript: ^6.0.3