name: iso-ucan
env:
  CI: true
  FORCE_COLOR: 1
on:
  push:
    branches:
      - main
    paths:
      - 'packages/iso-ucan/**'
      - .github/workflows/iso-ucan.yml
      - pnpm-lock.yaml
  pull_request:
    paths:
      - 'packages/iso-ucan/**'
      - .github/workflows/iso-ucan.yml
      - pnpm-lock.yaml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: pnpm
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm -r --filter iso-ucan run lint
      - run: pnpm -r --filter iso-ucan run test
      - run: pnpm -r --filter iso-ucan exec depcheck
